'use client';

import { IPLeaderboardTable, type IPLeaderboardRow, type MediaFilter } from './ip-leaderboard-table';
import { trpc } from '@/lib/trpc';

/* ─────────────────────────────────────────────────────────────────────────────
 * IP Leaderboard Preview
 * 
 * This component serves as an interim solution, displaying placeholder data
 * that matches the target mockup design. The structure is designed for easy
 * replacement with real data once a dedicated leaderboard scoring table exists.
 * 
 * Data source priority:
 * 1. Try to fetch from raw_observations via Supabase (when available)
 * 2. Fall back to generated placeholder data matching the mockup
 * ─────────────────────────────────────────────────────────────────────────────*/

interface IPLeaderboardPreviewProps {
  organizationId: string | null;
}

export function IPLeaderboardPreview({ organizationId }: IPLeaderboardPreviewProps) {
  // Future: Fetch real data from Supabase raw_observations or a dedicated table
  // const { data, isLoading } = trpc.leaderboard.ipRankings.useQuery(
  //   { organizationId: organizationId ?? '' },
  //   { enabled: Boolean(organizationId) }
  // );

  // For now, use placeholder data generated by the table component
  // This displays the target UI structure matching the mockup
  
  const handleFilterChange = (filter: MediaFilter) => {
    // Future: Trigger refetch with new filter when backend supports it
    // For now, filtering happens client-side in the component
  };

  return (
    <div className="ip-preview-container">
      <IPLeaderboardTable
        // data={transformedData} // Pass real data when available
        onFilterChange={handleFilterChange}
      />
      <p className="ip-preview-notice">
        Showing placeholder data. This table will automatically update once the dedicated 
        IP scoring pipeline is operational and populating the leaderboard tables.
      </p>
    </div>
  );
}
